### ISSUE TITLE
Final Tag Page: Provide information for why the tag was assigned 

### ISSUE THREAD

**Issue by eaquigley** [IQSS/DataTaggingLibrary#104]
On the Final Tag page, have more information for the user that explains why the tag was chosen. For example, at certain trigger points in the workflow when a question is answered a specific way, that's when a part of the tag is assigned. For those triggers there will be a one or two sentence that explains the laws that define that tag assignment, after the questionnaire, those sentences will appear to provide the user with information on why the tag was chosen based off their answers.

**Comment by michbarsinai** [comment]
This issue was moved to IQSS/DataTaggingServer#4
