### ISSUE TITLE
Add a "part" node, alter semantics of "section"

### ISSUE THREAD

**Issue by michbarsinai** [IQSS/DataTaggingLibrary#209]
Part nodes serve as a structural grouping for engineering purposes, as oppose to the logical grouping, done  by `[section]`: 

```
[-->id<
 [general graph goes here]
--]
```

Notes:
* `[call]` nodes can only call part nodes.
* When done executing `[section]` nodes, we always go to their `next`
* When done executing `[--part]` nodes, always go back to the `next` of the `call` that called the part.
* parts do not contain parts, but can contain anything else.

Parts are out to the normal node flow. So in the following file:
```
[a]
[b]
[-->xx<
  [x]
  [y]
--]
[c]
[d]
```

`next` field of the nodes is:
```
"main"->[a]->[b]->[c]->[d]
"parts[xx]"->[x]->[y]

Todo:
* [ ] update parser
* [ ] Update runtime and tests
* [ ] Update visualizations and validations 
* [ ] Update docs.

**Comment by MorVilozni** [comment]
https://github.com/IQSS/DataTaggingLibrary/commit/c01c00c7321a7d3b01d676c0df574d03065e7ad4

Todo:
* [x] update parser
* [x] Update runtime and tests
* [ ] Update visualizations and validations 
* [ ] Update docs.
